// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/agui-coder/simple-admin-product-rpc/ent/brand"
	"github.com/agui-coder/simple-admin-product-rpc/ent/category"
	"github.com/agui-coder/simple-admin-product-rpc/ent/comment"
	"github.com/agui-coder/simple-admin-product-rpc/ent/property"
	"github.com/agui-coder/simple-admin-product-rpc/ent/propertyvalue"
	"github.com/agui-coder/simple-admin-product-rpc/ent/schema"
	"github.com/agui-coder/simple-admin-product-rpc/ent/sku"
	"github.com/agui-coder/simple-admin-product-rpc/ent/spu"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandMixin := schema.Brand{}.Mixin()
	brandMixinHooks3 := brandMixin[3].Hooks()
	brand.Hooks[0] = brandMixinHooks3[0]
	brandMixinInters3 := brandMixin[3].Interceptors()
	brand.Interceptors[0] = brandMixinInters3[0]
	brandMixinFields0 := brandMixin[0].Fields()
	_ = brandMixinFields0
	brandMixinFields1 := brandMixin[1].Fields()
	_ = brandMixinFields1
	brandMixinFields2 := brandMixin[2].Fields()
	_ = brandMixinFields2
	brandFields := schema.Brand{}.Fields()
	_ = brandFields
	// brandDescCreatedAt is the schema descriptor for created_at field.
	brandDescCreatedAt := brandMixinFields0[1].Descriptor()
	// brand.DefaultCreatedAt holds the default value on creation for the created_at field.
	brand.DefaultCreatedAt = brandDescCreatedAt.Default.(func() time.Time)
	// brandDescUpdatedAt is the schema descriptor for updated_at field.
	brandDescUpdatedAt := brandMixinFields0[2].Descriptor()
	// brand.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	brand.DefaultUpdatedAt = brandDescUpdatedAt.Default.(func() time.Time)
	// brand.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	brand.UpdateDefaultUpdatedAt = brandDescUpdatedAt.UpdateDefault.(func() time.Time)
	// brandDescStatus is the schema descriptor for status field.
	brandDescStatus := brandMixinFields1[0].Descriptor()
	// brand.DefaultStatus holds the default value on creation for the status field.
	brand.DefaultStatus = brandDescStatus.Default.(uint8)
	// brandDescSort is the schema descriptor for sort field.
	brandDescSort := brandMixinFields2[0].Descriptor()
	// brand.DefaultSort holds the default value on creation for the sort field.
	brand.DefaultSort = brandDescSort.Default.(uint32)
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinHooks3 := categoryMixin[3].Hooks()
	category.Hooks[0] = categoryMixinHooks3[0]
	categoryMixinInters3 := categoryMixin[3].Interceptors()
	category.Interceptors[0] = categoryMixinInters3[0]
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryMixinFields1 := categoryMixin[1].Fields()
	_ = categoryMixinFields1
	categoryMixinFields2 := categoryMixin[2].Fields()
	_ = categoryMixinFields2
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[1].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields0[2].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescStatus is the schema descriptor for status field.
	categoryDescStatus := categoryMixinFields1[0].Descriptor()
	// category.DefaultStatus holds the default value on creation for the status field.
	category.DefaultStatus = categoryDescStatus.Default.(uint8)
	// categoryDescSort is the schema descriptor for sort field.
	categoryDescSort := categoryMixinFields2[0].Descriptor()
	// category.DefaultSort holds the default value on creation for the sort field.
	category.DefaultSort = categoryDescSort.Default.(uint32)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinHooks1 := commentMixin[1].Hooks()
	comment.Hooks[0] = commentMixinHooks1[0]
	commentMixinInters1 := commentMixin[1].Interceptors()
	comment.Interceptors[0] = commentMixinInters1[0]
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[1].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[2].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	propertyMixin := schema.Property{}.Mixin()
	propertyMixinHooks2 := propertyMixin[2].Hooks()
	property.Hooks[0] = propertyMixinHooks2[0]
	propertyMixinInters2 := propertyMixin[2].Interceptors()
	property.Interceptors[0] = propertyMixinInters2[0]
	propertyMixinFields0 := propertyMixin[0].Fields()
	_ = propertyMixinFields0
	propertyMixinFields1 := propertyMixin[1].Fields()
	_ = propertyMixinFields1
	propertyFields := schema.Property{}.Fields()
	_ = propertyFields
	// propertyDescCreatedAt is the schema descriptor for created_at field.
	propertyDescCreatedAt := propertyMixinFields0[1].Descriptor()
	// property.DefaultCreatedAt holds the default value on creation for the created_at field.
	property.DefaultCreatedAt = propertyDescCreatedAt.Default.(func() time.Time)
	// propertyDescUpdatedAt is the schema descriptor for updated_at field.
	propertyDescUpdatedAt := propertyMixinFields0[2].Descriptor()
	// property.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	property.DefaultUpdatedAt = propertyDescUpdatedAt.Default.(func() time.Time)
	// property.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	property.UpdateDefaultUpdatedAt = propertyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// propertyDescStatus is the schema descriptor for status field.
	propertyDescStatus := propertyMixinFields1[0].Descriptor()
	// property.DefaultStatus holds the default value on creation for the status field.
	property.DefaultStatus = propertyDescStatus.Default.(uint8)
	propertyvalueMixin := schema.PropertyValue{}.Mixin()
	propertyvalueMixinHooks1 := propertyvalueMixin[1].Hooks()
	propertyvalue.Hooks[0] = propertyvalueMixinHooks1[0]
	propertyvalueMixinInters1 := propertyvalueMixin[1].Interceptors()
	propertyvalue.Interceptors[0] = propertyvalueMixinInters1[0]
	propertyvalueMixinFields0 := propertyvalueMixin[0].Fields()
	_ = propertyvalueMixinFields0
	propertyvalueFields := schema.PropertyValue{}.Fields()
	_ = propertyvalueFields
	// propertyvalueDescCreatedAt is the schema descriptor for created_at field.
	propertyvalueDescCreatedAt := propertyvalueMixinFields0[1].Descriptor()
	// propertyvalue.DefaultCreatedAt holds the default value on creation for the created_at field.
	propertyvalue.DefaultCreatedAt = propertyvalueDescCreatedAt.Default.(func() time.Time)
	// propertyvalueDescUpdatedAt is the schema descriptor for updated_at field.
	propertyvalueDescUpdatedAt := propertyvalueMixinFields0[2].Descriptor()
	// propertyvalue.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	propertyvalue.DefaultUpdatedAt = propertyvalueDescUpdatedAt.Default.(func() time.Time)
	// propertyvalue.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	propertyvalue.UpdateDefaultUpdatedAt = propertyvalueDescUpdatedAt.UpdateDefault.(func() time.Time)
	skuMixin := schema.Sku{}.Mixin()
	skuMixinHooks1 := skuMixin[1].Hooks()
	sku.Hooks[0] = skuMixinHooks1[0]
	skuMixinInters1 := skuMixin[1].Interceptors()
	sku.Interceptors[0] = skuMixinInters1[0]
	skuMixinFields0 := skuMixin[0].Fields()
	_ = skuMixinFields0
	skuFields := schema.Sku{}.Fields()
	_ = skuFields
	// skuDescCreatedAt is the schema descriptor for created_at field.
	skuDescCreatedAt := skuMixinFields0[1].Descriptor()
	// sku.DefaultCreatedAt holds the default value on creation for the created_at field.
	sku.DefaultCreatedAt = skuDescCreatedAt.Default.(func() time.Time)
	// skuDescUpdatedAt is the schema descriptor for updated_at field.
	skuDescUpdatedAt := skuMixinFields0[2].Descriptor()
	// sku.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sku.DefaultUpdatedAt = skuDescUpdatedAt.Default.(func() time.Time)
	// sku.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sku.UpdateDefaultUpdatedAt = skuDescUpdatedAt.UpdateDefault.(func() time.Time)
	spuMixin := schema.Spu{}.Mixin()
	spuMixinHooks3 := spuMixin[3].Hooks()
	spu.Hooks[0] = spuMixinHooks3[0]
	spuMixinInters3 := spuMixin[3].Interceptors()
	spu.Interceptors[0] = spuMixinInters3[0]
	spuMixinFields0 := spuMixin[0].Fields()
	_ = spuMixinFields0
	spuMixinFields1 := spuMixin[1].Fields()
	_ = spuMixinFields1
	spuMixinFields2 := spuMixin[2].Fields()
	_ = spuMixinFields2
	spuFields := schema.Spu{}.Fields()
	_ = spuFields
	// spuDescCreatedAt is the schema descriptor for created_at field.
	spuDescCreatedAt := spuMixinFields0[1].Descriptor()
	// spu.DefaultCreatedAt holds the default value on creation for the created_at field.
	spu.DefaultCreatedAt = spuDescCreatedAt.Default.(func() time.Time)
	// spuDescUpdatedAt is the schema descriptor for updated_at field.
	spuDescUpdatedAt := spuMixinFields0[2].Descriptor()
	// spu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	spu.DefaultUpdatedAt = spuDescUpdatedAt.Default.(func() time.Time)
	// spu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	spu.UpdateDefaultUpdatedAt = spuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// spuDescStatus is the schema descriptor for status field.
	spuDescStatus := spuMixinFields1[0].Descriptor()
	// spu.DefaultStatus holds the default value on creation for the status field.
	spu.DefaultStatus = spuDescStatus.Default.(uint8)
	// spuDescSort is the schema descriptor for sort field.
	spuDescSort := spuMixinFields2[0].Descriptor()
	// spu.DefaultSort holds the default value on creation for the sort field.
	spu.DefaultSort = spuDescSort.Default.(uint32)
}

const (
	Version = "v0.12.4"                                         // Version of ent codegen.
	Sum     = "h1:LddPnAyxls/O7DTXZvUGDj0NZIdGSu317+aoNLJWbD8=" // Sum of ent codegen.
)
