// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/agui-coder/simple-admin-product-rpc/ent/brand"
	"github.com/agui-coder/simple-admin-product-rpc/ent/spu"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BrandCreate is the builder for creating a Brand entity.
type BrandCreate struct {
	config
	mutation *BrandMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (bc *BrandCreate) SetCreatedAt(t time.Time) *BrandCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BrandCreate) SetNillableCreatedAt(t *time.Time) *BrandCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BrandCreate) SetUpdatedAt(t time.Time) *BrandCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BrandCreate) SetNillableUpdatedAt(t *time.Time) *BrandCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetStatus sets the "status" field.
func (bc *BrandCreate) SetStatus(u uint8) *BrandCreate {
	bc.mutation.SetStatus(u)
	return bc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bc *BrandCreate) SetNillableStatus(u *uint8) *BrandCreate {
	if u != nil {
		bc.SetStatus(*u)
	}
	return bc
}

// SetSort sets the "sort" field.
func (bc *BrandCreate) SetSort(u uint32) *BrandCreate {
	bc.mutation.SetSort(u)
	return bc
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (bc *BrandCreate) SetNillableSort(u *uint32) *BrandCreate {
	if u != nil {
		bc.SetSort(*u)
	}
	return bc
}

// SetDeletedAt sets the "deleted_at" field.
func (bc *BrandCreate) SetDeletedAt(t time.Time) *BrandCreate {
	bc.mutation.SetDeletedAt(t)
	return bc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (bc *BrandCreate) SetNillableDeletedAt(t *time.Time) *BrandCreate {
	if t != nil {
		bc.SetDeletedAt(*t)
	}
	return bc
}

// SetName sets the "name" field.
func (bc *BrandCreate) SetName(s string) *BrandCreate {
	bc.mutation.SetName(s)
	return bc
}

// SetPicURL sets the "pic_url" field.
func (bc *BrandCreate) SetPicURL(s string) *BrandCreate {
	bc.mutation.SetPicURL(s)
	return bc
}

// SetDescription sets the "description" field.
func (bc *BrandCreate) SetDescription(s string) *BrandCreate {
	bc.mutation.SetDescription(s)
	return bc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (bc *BrandCreate) SetNillableDescription(s *string) *BrandCreate {
	if s != nil {
		bc.SetDescription(*s)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BrandCreate) SetID(u uint64) *BrandCreate {
	bc.mutation.SetID(u)
	return bc
}

// AddSpuIDs adds the "spus" edge to the Spu entity by IDs.
func (bc *BrandCreate) AddSpuIDs(ids ...uint64) *BrandCreate {
	bc.mutation.AddSpuIDs(ids...)
	return bc
}

// AddSpus adds the "spus" edges to the Spu entity.
func (bc *BrandCreate) AddSpus(s ...*Spu) *BrandCreate {
	ids := make([]uint64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return bc.AddSpuIDs(ids...)
}

// Mutation returns the BrandMutation object of the builder.
func (bc *BrandCreate) Mutation() *BrandMutation {
	return bc.mutation
}

// Save creates the Brand in the database.
func (bc *BrandCreate) Save(ctx context.Context) (*Brand, error) {
	if err := bc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BrandCreate) SaveX(ctx context.Context) *Brand {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BrandCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BrandCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BrandCreate) defaults() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		if brand.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized brand.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := brand.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		if brand.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized brand.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := brand.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.Status(); !ok {
		v := brand.DefaultStatus
		bc.mutation.SetStatus(v)
	}
	if _, ok := bc.mutation.Sort(); !ok {
		v := brand.DefaultSort
		bc.mutation.SetSort(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (bc *BrandCreate) check() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Brand.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Brand.updated_at"`)}
	}
	if _, ok := bc.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "Brand.sort"`)}
	}
	if _, ok := bc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Brand.name"`)}
	}
	if _, ok := bc.mutation.PicURL(); !ok {
		return &ValidationError{Name: "pic_url", err: errors.New(`ent: missing required field "Brand.pic_url"`)}
	}
	return nil
}

func (bc *BrandCreate) sqlSave(ctx context.Context) (*Brand, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BrandCreate) createSpec() (*Brand, *sqlgraph.CreateSpec) {
	var (
		_node = &Brand{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(brand.Table, sqlgraph.NewFieldSpec(brand.FieldID, field.TypeUint64))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(brand.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(brand.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := bc.mutation.Status(); ok {
		_spec.SetField(brand.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := bc.mutation.Sort(); ok {
		_spec.SetField(brand.FieldSort, field.TypeUint32, value)
		_node.Sort = value
	}
	if value, ok := bc.mutation.DeletedAt(); ok {
		_spec.SetField(brand.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := bc.mutation.Name(); ok {
		_spec.SetField(brand.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := bc.mutation.PicURL(); ok {
		_spec.SetField(brand.FieldPicURL, field.TypeString, value)
		_node.PicURL = value
	}
	if value, ok := bc.mutation.Description(); ok {
		_spec.SetField(brand.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := bc.mutation.SpusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   brand.SpusTable,
			Columns: []string{brand.SpusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BrandCreateBulk is the builder for creating many Brand entities in bulk.
type BrandCreateBulk struct {
	config
	err      error
	builders []*BrandCreate
}

// Save creates the Brand entities in the database.
func (bcb *BrandCreateBulk) Save(ctx context.Context) ([]*Brand, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Brand, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BrandMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BrandCreateBulk) SaveX(ctx context.Context) []*Brand {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BrandCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BrandCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
