// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"github.com/agui-coder/simple-admin-product-rpc/ent/predicate"
	"github.com/agui-coder/simple-admin-product-rpc/ent/property"
	"github.com/agui-coder/simple-admin-product-rpc/ent/propertyvalue"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PropertyValueQuery is the builder for querying PropertyValue entities.
type PropertyValueQuery struct {
	config
	ctx           *QueryContext
	order         []propertyvalue.OrderOption
	inters        []Interceptor
	predicates    []predicate.PropertyValue
	withPropertys *PropertyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PropertyValueQuery builder.
func (pvq *PropertyValueQuery) Where(ps ...predicate.PropertyValue) *PropertyValueQuery {
	pvq.predicates = append(pvq.predicates, ps...)
	return pvq
}

// Limit the number of records to be returned by this query.
func (pvq *PropertyValueQuery) Limit(limit int) *PropertyValueQuery {
	pvq.ctx.Limit = &limit
	return pvq
}

// Offset to start from.
func (pvq *PropertyValueQuery) Offset(offset int) *PropertyValueQuery {
	pvq.ctx.Offset = &offset
	return pvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pvq *PropertyValueQuery) Unique(unique bool) *PropertyValueQuery {
	pvq.ctx.Unique = &unique
	return pvq
}

// Order specifies how the records should be ordered.
func (pvq *PropertyValueQuery) Order(o ...propertyvalue.OrderOption) *PropertyValueQuery {
	pvq.order = append(pvq.order, o...)
	return pvq
}

// QueryPropertys chains the current query on the "propertys" edge.
func (pvq *PropertyValueQuery) QueryPropertys() *PropertyQuery {
	query := (&PropertyClient{config: pvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(propertyvalue.Table, propertyvalue.FieldID, selector),
			sqlgraph.To(property.Table, property.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, propertyvalue.PropertysTable, propertyvalue.PropertysColumn),
		)
		fromU = sqlgraph.SetNeighbors(pvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PropertyValue entity from the query.
// Returns a *NotFoundError when no PropertyValue was found.
func (pvq *PropertyValueQuery) First(ctx context.Context) (*PropertyValue, error) {
	nodes, err := pvq.Limit(1).All(setContextOp(ctx, pvq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{propertyvalue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pvq *PropertyValueQuery) FirstX(ctx context.Context) *PropertyValue {
	node, err := pvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PropertyValue ID from the query.
// Returns a *NotFoundError when no PropertyValue ID was found.
func (pvq *PropertyValueQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = pvq.Limit(1).IDs(setContextOp(ctx, pvq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{propertyvalue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pvq *PropertyValueQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := pvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PropertyValue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PropertyValue entity is found.
// Returns a *NotFoundError when no PropertyValue entities are found.
func (pvq *PropertyValueQuery) Only(ctx context.Context) (*PropertyValue, error) {
	nodes, err := pvq.Limit(2).All(setContextOp(ctx, pvq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{propertyvalue.Label}
	default:
		return nil, &NotSingularError{propertyvalue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pvq *PropertyValueQuery) OnlyX(ctx context.Context) *PropertyValue {
	node, err := pvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PropertyValue ID in the query.
// Returns a *NotSingularError when more than one PropertyValue ID is found.
// Returns a *NotFoundError when no entities are found.
func (pvq *PropertyValueQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = pvq.Limit(2).IDs(setContextOp(ctx, pvq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{propertyvalue.Label}
	default:
		err = &NotSingularError{propertyvalue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pvq *PropertyValueQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := pvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PropertyValues.
func (pvq *PropertyValueQuery) All(ctx context.Context) ([]*PropertyValue, error) {
	ctx = setContextOp(ctx, pvq.ctx, "All")
	if err := pvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PropertyValue, *PropertyValueQuery]()
	return withInterceptors[[]*PropertyValue](ctx, pvq, qr, pvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pvq *PropertyValueQuery) AllX(ctx context.Context) []*PropertyValue {
	nodes, err := pvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PropertyValue IDs.
func (pvq *PropertyValueQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if pvq.ctx.Unique == nil && pvq.path != nil {
		pvq.Unique(true)
	}
	ctx = setContextOp(ctx, pvq.ctx, "IDs")
	if err = pvq.Select(propertyvalue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pvq *PropertyValueQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := pvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pvq *PropertyValueQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pvq.ctx, "Count")
	if err := pvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pvq, querierCount[*PropertyValueQuery](), pvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pvq *PropertyValueQuery) CountX(ctx context.Context) int {
	count, err := pvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pvq *PropertyValueQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pvq.ctx, "Exist")
	switch _, err := pvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pvq *PropertyValueQuery) ExistX(ctx context.Context) bool {
	exist, err := pvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PropertyValueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pvq *PropertyValueQuery) Clone() *PropertyValueQuery {
	if pvq == nil {
		return nil
	}
	return &PropertyValueQuery{
		config:        pvq.config,
		ctx:           pvq.ctx.Clone(),
		order:         append([]propertyvalue.OrderOption{}, pvq.order...),
		inters:        append([]Interceptor{}, pvq.inters...),
		predicates:    append([]predicate.PropertyValue{}, pvq.predicates...),
		withPropertys: pvq.withPropertys.Clone(),
		// clone intermediate query.
		sql:  pvq.sql.Clone(),
		path: pvq.path,
	}
}

// WithPropertys tells the query-builder to eager-load the nodes that are connected to
// the "propertys" edge. The optional arguments are used to configure the query builder of the edge.
func (pvq *PropertyValueQuery) WithPropertys(opts ...func(*PropertyQuery)) *PropertyValueQuery {
	query := (&PropertyClient{config: pvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pvq.withPropertys = query
	return pvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PropertyValue.Query().
//		GroupBy(propertyvalue.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pvq *PropertyValueQuery) GroupBy(field string, fields ...string) *PropertyValueGroupBy {
	pvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PropertyValueGroupBy{build: pvq}
	grbuild.flds = &pvq.ctx.Fields
	grbuild.label = propertyvalue.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PropertyValue.Query().
//		Select(propertyvalue.FieldCreatedAt).
//		Scan(ctx, &v)
func (pvq *PropertyValueQuery) Select(fields ...string) *PropertyValueSelect {
	pvq.ctx.Fields = append(pvq.ctx.Fields, fields...)
	sbuild := &PropertyValueSelect{PropertyValueQuery: pvq}
	sbuild.label = propertyvalue.Label
	sbuild.flds, sbuild.scan = &pvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PropertyValueSelect configured with the given aggregations.
func (pvq *PropertyValueQuery) Aggregate(fns ...AggregateFunc) *PropertyValueSelect {
	return pvq.Select().Aggregate(fns...)
}

func (pvq *PropertyValueQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pvq); err != nil {
				return err
			}
		}
	}
	for _, f := range pvq.ctx.Fields {
		if !propertyvalue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pvq.path != nil {
		prev, err := pvq.path(ctx)
		if err != nil {
			return err
		}
		pvq.sql = prev
	}
	return nil
}

func (pvq *PropertyValueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PropertyValue, error) {
	var (
		nodes       = []*PropertyValue{}
		_spec       = pvq.querySpec()
		loadedTypes = [1]bool{
			pvq.withPropertys != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PropertyValue).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PropertyValue{config: pvq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pvq.withPropertys; query != nil {
		if err := pvq.loadPropertys(ctx, query, nodes, nil,
			func(n *PropertyValue, e *Property) { n.Edges.Propertys = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pvq *PropertyValueQuery) loadPropertys(ctx context.Context, query *PropertyQuery, nodes []*PropertyValue, init func(*PropertyValue), assign func(*PropertyValue, *Property)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*PropertyValue)
	for i := range nodes {
		fk := nodes[i].PropertyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(property.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "property_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pvq *PropertyValueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pvq.querySpec()
	_spec.Node.Columns = pvq.ctx.Fields
	if len(pvq.ctx.Fields) > 0 {
		_spec.Unique = pvq.ctx.Unique != nil && *pvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pvq.driver, _spec)
}

func (pvq *PropertyValueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(propertyvalue.Table, propertyvalue.Columns, sqlgraph.NewFieldSpec(propertyvalue.FieldID, field.TypeUint64))
	_spec.From = pvq.sql
	if unique := pvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pvq.path != nil {
		_spec.Unique = true
	}
	if fields := pvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, propertyvalue.FieldID)
		for i := range fields {
			if fields[i] != propertyvalue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if pvq.withPropertys != nil {
			_spec.Node.AddColumnOnce(propertyvalue.FieldPropertyID)
		}
	}
	if ps := pvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pvq *PropertyValueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pvq.driver.Dialect())
	t1 := builder.Table(propertyvalue.Table)
	columns := pvq.ctx.Fields
	if len(columns) == 0 {
		columns = propertyvalue.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pvq.sql != nil {
		selector = pvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pvq.ctx.Unique != nil && *pvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pvq.predicates {
		p(selector)
	}
	for _, p := range pvq.order {
		p(selector)
	}
	if offset := pvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PropertyValueGroupBy is the group-by builder for PropertyValue entities.
type PropertyValueGroupBy struct {
	selector
	build *PropertyValueQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pvgb *PropertyValueGroupBy) Aggregate(fns ...AggregateFunc) *PropertyValueGroupBy {
	pvgb.fns = append(pvgb.fns, fns...)
	return pvgb
}

// Scan applies the selector query and scans the result into the given value.
func (pvgb *PropertyValueGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pvgb.build.ctx, "GroupBy")
	if err := pvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PropertyValueQuery, *PropertyValueGroupBy](ctx, pvgb.build, pvgb, pvgb.build.inters, v)
}

func (pvgb *PropertyValueGroupBy) sqlScan(ctx context.Context, root *PropertyValueQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pvgb.fns))
	for _, fn := range pvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pvgb.flds)+len(pvgb.fns))
		for _, f := range *pvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PropertyValueSelect is the builder for selecting fields of PropertyValue entities.
type PropertyValueSelect struct {
	*PropertyValueQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pvs *PropertyValueSelect) Aggregate(fns ...AggregateFunc) *PropertyValueSelect {
	pvs.fns = append(pvs.fns, fns...)
	return pvs
}

// Scan applies the selector query and scans the result into the given value.
func (pvs *PropertyValueSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pvs.ctx, "Select")
	if err := pvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PropertyValueQuery, *PropertyValueSelect](ctx, pvs.PropertyValueQuery, pvs, pvs.inters, v)
}

func (pvs *PropertyValueSelect) sqlScan(ctx context.Context, root *PropertyValueQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pvs.fns))
	for _, fn := range pvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
