// Code generated by ent, DO NOT EDIT.

package ent

import (
	entType "github.com/agui-coder/simple-admin-product-rpc/ent/schema/enttype"
	"time"
)

// set field if value's pointer is not nil.
func (b *BrandUpdate) SetNotNilUpdatedAt(value *time.Time) *BrandUpdate {
	if value != nil {
		return b.SetUpdatedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdateOne) SetNotNilUpdatedAt(value *time.Time) *BrandUpdateOne {
	if value != nil {
		return b.SetUpdatedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandCreate) SetNotNilUpdatedAt(value *time.Time) *BrandCreate {
	if value != nil {
		return b.SetUpdatedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdate) SetNotNilStatus(value *uint8) *BrandUpdate {
	if value != nil {
		return b.SetStatus(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdateOne) SetNotNilStatus(value *uint8) *BrandUpdateOne {
	if value != nil {
		return b.SetStatus(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandCreate) SetNotNilStatus(value *uint8) *BrandCreate {
	if value != nil {
		return b.SetStatus(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdate) SetNotNilSort(value *uint32) *BrandUpdate {
	if value != nil {
		return b.SetSort(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdateOne) SetNotNilSort(value *uint32) *BrandUpdateOne {
	if value != nil {
		return b.SetSort(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandCreate) SetNotNilSort(value *uint32) *BrandCreate {
	if value != nil {
		return b.SetSort(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdate) SetNotNilDeletedAt(value *time.Time) *BrandUpdate {
	if value != nil {
		return b.SetDeletedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdateOne) SetNotNilDeletedAt(value *time.Time) *BrandUpdateOne {
	if value != nil {
		return b.SetDeletedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandCreate) SetNotNilDeletedAt(value *time.Time) *BrandCreate {
	if value != nil {
		return b.SetDeletedAt(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdate) SetNotNilName(value *string) *BrandUpdate {
	if value != nil {
		return b.SetName(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdateOne) SetNotNilName(value *string) *BrandUpdateOne {
	if value != nil {
		return b.SetName(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandCreate) SetNotNilName(value *string) *BrandCreate {
	if value != nil {
		return b.SetName(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdate) SetNotNilPicURL(value *string) *BrandUpdate {
	if value != nil {
		return b.SetPicURL(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdateOne) SetNotNilPicURL(value *string) *BrandUpdateOne {
	if value != nil {
		return b.SetPicURL(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandCreate) SetNotNilPicURL(value *string) *BrandCreate {
	if value != nil {
		return b.SetPicURL(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdate) SetNotNilDescription(value *string) *BrandUpdate {
	if value != nil {
		return b.SetDescription(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandUpdateOne) SetNotNilDescription(value *string) *BrandUpdateOne {
	if value != nil {
		return b.SetDescription(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (b *BrandCreate) SetNotNilDescription(value *string) *BrandCreate {
	if value != nil {
		return b.SetDescription(*value)
	}
	return b
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilUpdatedAt(value *time.Time) *CategoryUpdate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CategoryUpdateOne {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilUpdatedAt(value *time.Time) *CategoryCreate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilStatus(value *uint8) *CategoryUpdate {
	if value != nil {
		return c.SetStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilStatus(value *uint8) *CategoryUpdateOne {
	if value != nil {
		return c.SetStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilStatus(value *uint8) *CategoryCreate {
	if value != nil {
		return c.SetStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilSort(value *uint32) *CategoryUpdate {
	if value != nil {
		return c.SetSort(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilSort(value *uint32) *CategoryUpdateOne {
	if value != nil {
		return c.SetSort(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilSort(value *uint32) *CategoryCreate {
	if value != nil {
		return c.SetSort(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilDeletedAt(value *time.Time) *CategoryUpdate {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilDeletedAt(value *time.Time) *CategoryUpdateOne {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilDeletedAt(value *time.Time) *CategoryCreate {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilParentID(value *uint64) *CategoryUpdate {
	if value != nil {
		return c.SetParentID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilParentID(value *uint64) *CategoryUpdateOne {
	if value != nil {
		return c.SetParentID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilParentID(value *uint64) *CategoryCreate {
	if value != nil {
		return c.SetParentID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilName(value *string) *CategoryUpdate {
	if value != nil {
		return c.SetName(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilName(value *string) *CategoryUpdateOne {
	if value != nil {
		return c.SetName(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilName(value *string) *CategoryCreate {
	if value != nil {
		return c.SetName(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilPicURL(value *string) *CategoryUpdate {
	if value != nil {
		return c.SetPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilPicURL(value *string) *CategoryUpdateOne {
	if value != nil {
		return c.SetPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilPicURL(value *string) *CategoryCreate {
	if value != nil {
		return c.SetPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilBigPicURL(value *string) *CategoryUpdate {
	if value != nil {
		return c.SetBigPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilBigPicURL(value *string) *CategoryUpdateOne {
	if value != nil {
		return c.SetBigPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilBigPicURL(value *string) *CategoryCreate {
	if value != nil {
		return c.SetBigPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilUpdatedAt(value *time.Time) *CommentUpdate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CommentUpdateOne {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilUpdatedAt(value *time.Time) *CommentCreate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilDeletedAt(value *time.Time) *CommentUpdate {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilDeletedAt(value *time.Time) *CommentUpdateOne {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilDeletedAt(value *time.Time) *CommentCreate {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilUserID(value *uint64) *CommentUpdate {
	if value != nil {
		return c.SetUserID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilUserID(value *uint64) *CommentUpdateOne {
	if value != nil {
		return c.SetUserID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilUserID(value *uint64) *CommentCreate {
	if value != nil {
		return c.SetUserID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilUserNickname(value *string) *CommentUpdate {
	if value != nil {
		return c.SetUserNickname(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilUserNickname(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetUserNickname(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilUserNickname(value *string) *CommentCreate {
	if value != nil {
		return c.SetUserNickname(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilUserAvatar(value *string) *CommentUpdate {
	if value != nil {
		return c.SetUserAvatar(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilUserAvatar(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetUserAvatar(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilUserAvatar(value *string) *CommentCreate {
	if value != nil {
		return c.SetUserAvatar(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilAnonymous(value *bool) *CommentUpdate {
	if value != nil {
		return c.SetAnonymous(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilAnonymous(value *bool) *CommentUpdateOne {
	if value != nil {
		return c.SetAnonymous(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilAnonymous(value *bool) *CommentCreate {
	if value != nil {
		return c.SetAnonymous(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilOrderID(value *uint64) *CommentUpdate {
	if value != nil {
		return c.SetOrderID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilOrderID(value *uint64) *CommentUpdateOne {
	if value != nil {
		return c.SetOrderID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilOrderID(value *uint64) *CommentCreate {
	if value != nil {
		return c.SetOrderID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilOrderItemID(value *uint64) *CommentUpdate {
	if value != nil {
		return c.SetOrderItemID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilOrderItemID(value *uint64) *CommentUpdateOne {
	if value != nil {
		return c.SetOrderItemID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilOrderItemID(value *uint64) *CommentCreate {
	if value != nil {
		return c.SetOrderItemID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilSpuID(value *uint64) *CommentUpdate {
	if value != nil {
		return c.SetSpuID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilSpuID(value *uint64) *CommentUpdateOne {
	if value != nil {
		return c.SetSpuID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilSpuID(value *uint64) *CommentCreate {
	if value != nil {
		return c.SetSpuID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilSpuName(value *string) *CommentUpdate {
	if value != nil {
		return c.SetSpuName(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilSpuName(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetSpuName(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilSpuName(value *string) *CommentCreate {
	if value != nil {
		return c.SetSpuName(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilSkuID(value *uint64) *CommentUpdate {
	if value != nil {
		return c.SetSkuID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilSkuID(value *uint64) *CommentUpdateOne {
	if value != nil {
		return c.SetSkuID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilSkuID(value *uint64) *CommentCreate {
	if value != nil {
		return c.SetSkuID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilSkuPicURL(value *string) *CommentUpdate {
	if value != nil {
		return c.SetSkuPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilSkuPicURL(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetSkuPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilSkuPicURL(value *string) *CommentCreate {
	if value != nil {
		return c.SetSkuPicURL(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilSkuProperties(value *[]entType.SkuProperty) *CommentUpdate {
	if value != nil {
		return c.SetSkuProperties(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilSkuProperties(value *[]entType.SkuProperty) *CommentUpdateOne {
	if value != nil {
		return c.SetSkuProperties(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilSkuProperties(value *[]entType.SkuProperty) *CommentCreate {
	if value != nil {
		return c.SetSkuProperties(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilVisible(value *bool) *CommentUpdate {
	if value != nil {
		return c.SetVisible(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilVisible(value *bool) *CommentUpdateOne {
	if value != nil {
		return c.SetVisible(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilVisible(value *bool) *CommentCreate {
	if value != nil {
		return c.SetVisible(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilScores(value *int8) *CommentUpdate {
	if value != nil {
		return c.SetScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilScores(value *int8) *CommentUpdateOne {
	if value != nil {
		return c.SetScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilScores(value *int8) *CommentCreate {
	if value != nil {
		return c.SetScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilDescriptionScores(value *int8) *CommentUpdate {
	if value != nil {
		return c.SetDescriptionScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilDescriptionScores(value *int8) *CommentUpdateOne {
	if value != nil {
		return c.SetDescriptionScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilDescriptionScores(value *int8) *CommentCreate {
	if value != nil {
		return c.SetDescriptionScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilBenefitScores(value *int8) *CommentUpdate {
	if value != nil {
		return c.SetBenefitScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilBenefitScores(value *int8) *CommentUpdateOne {
	if value != nil {
		return c.SetBenefitScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilBenefitScores(value *int8) *CommentCreate {
	if value != nil {
		return c.SetBenefitScores(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilContent(value *string) *CommentUpdate {
	if value != nil {
		return c.SetContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilContent(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilContent(value *string) *CommentCreate {
	if value != nil {
		return c.SetContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilPicUrls(value *string) *CommentUpdate {
	if value != nil {
		return c.SetPicUrls(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilPicUrls(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetPicUrls(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilPicUrls(value *string) *CommentCreate {
	if value != nil {
		return c.SetPicUrls(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilReplyStatus(value *bool) *CommentUpdate {
	if value != nil {
		return c.SetReplyStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilReplyStatus(value *bool) *CommentUpdateOne {
	if value != nil {
		return c.SetReplyStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilReplyStatus(value *bool) *CommentCreate {
	if value != nil {
		return c.SetReplyStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilReplyUserID(value *int) *CommentUpdate {
	if value != nil {
		return c.SetReplyUserID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilReplyUserID(value *int) *CommentUpdateOne {
	if value != nil {
		return c.SetReplyUserID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilReplyUserID(value *int) *CommentCreate {
	if value != nil {
		return c.SetReplyUserID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilReplyContent(value *string) *CommentUpdate {
	if value != nil {
		return c.SetReplyContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilReplyContent(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetReplyContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilReplyContent(value *string) *CommentCreate {
	if value != nil {
		return c.SetReplyContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilReplyTime(value *time.Time) *CommentUpdate {
	if value != nil {
		return c.SetReplyTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilReplyTime(value *time.Time) *CommentUpdateOne {
	if value != nil {
		return c.SetReplyTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilReplyTime(value *time.Time) *CommentCreate {
	if value != nil {
		return c.SetReplyTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdate) SetNotNilUpdatedAt(value *time.Time) *PropertyUpdate {
	if value != nil {
		return pr.SetUpdatedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdateOne) SetNotNilUpdatedAt(value *time.Time) *PropertyUpdateOne {
	if value != nil {
		return pr.SetUpdatedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyCreate) SetNotNilUpdatedAt(value *time.Time) *PropertyCreate {
	if value != nil {
		return pr.SetUpdatedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdate) SetNotNilStatus(value *uint8) *PropertyUpdate {
	if value != nil {
		return pr.SetStatus(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdateOne) SetNotNilStatus(value *uint8) *PropertyUpdateOne {
	if value != nil {
		return pr.SetStatus(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyCreate) SetNotNilStatus(value *uint8) *PropertyCreate {
	if value != nil {
		return pr.SetStatus(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdate) SetNotNilDeletedAt(value *time.Time) *PropertyUpdate {
	if value != nil {
		return pr.SetDeletedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdateOne) SetNotNilDeletedAt(value *time.Time) *PropertyUpdateOne {
	if value != nil {
		return pr.SetDeletedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyCreate) SetNotNilDeletedAt(value *time.Time) *PropertyCreate {
	if value != nil {
		return pr.SetDeletedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdate) SetNotNilName(value *string) *PropertyUpdate {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdateOne) SetNotNilName(value *string) *PropertyUpdateOne {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyCreate) SetNotNilName(value *string) *PropertyCreate {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdate) SetNotNilRemark(value *string) *PropertyUpdate {
	if value != nil {
		return pr.SetRemark(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyUpdateOne) SetNotNilRemark(value *string) *PropertyUpdateOne {
	if value != nil {
		return pr.SetRemark(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *PropertyCreate) SetNotNilRemark(value *string) *PropertyCreate {
	if value != nil {
		return pr.SetRemark(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdate) SetNotNilUpdatedAt(value *time.Time) *PropertyValueUpdate {
	if value != nil {
		return pv.SetUpdatedAt(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdateOne) SetNotNilUpdatedAt(value *time.Time) *PropertyValueUpdateOne {
	if value != nil {
		return pv.SetUpdatedAt(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueCreate) SetNotNilUpdatedAt(value *time.Time) *PropertyValueCreate {
	if value != nil {
		return pv.SetUpdatedAt(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdate) SetNotNilDeletedAt(value *time.Time) *PropertyValueUpdate {
	if value != nil {
		return pv.SetDeletedAt(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdateOne) SetNotNilDeletedAt(value *time.Time) *PropertyValueUpdateOne {
	if value != nil {
		return pv.SetDeletedAt(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueCreate) SetNotNilDeletedAt(value *time.Time) *PropertyValueCreate {
	if value != nil {
		return pv.SetDeletedAt(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdate) SetNotNilPropertyID(value *uint64) *PropertyValueUpdate {
	if value != nil {
		return pv.SetPropertyID(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdateOne) SetNotNilPropertyID(value *uint64) *PropertyValueUpdateOne {
	if value != nil {
		return pv.SetPropertyID(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueCreate) SetNotNilPropertyID(value *uint64) *PropertyValueCreate {
	if value != nil {
		return pv.SetPropertyID(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdate) SetNotNilName(value *string) *PropertyValueUpdate {
	if value != nil {
		return pv.SetName(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdateOne) SetNotNilName(value *string) *PropertyValueUpdateOne {
	if value != nil {
		return pv.SetName(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueCreate) SetNotNilName(value *string) *PropertyValueCreate {
	if value != nil {
		return pv.SetName(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdate) SetNotNilRemark(value *string) *PropertyValueUpdate {
	if value != nil {
		return pv.SetRemark(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueUpdateOne) SetNotNilRemark(value *string) *PropertyValueUpdateOne {
	if value != nil {
		return pv.SetRemark(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (pv *PropertyValueCreate) SetNotNilRemark(value *string) *PropertyValueCreate {
	if value != nil {
		return pv.SetRemark(*value)
	}
	return pv
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilUpdatedAt(value *time.Time) *SkuUpdate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilUpdatedAt(value *time.Time) *SkuUpdateOne {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilUpdatedAt(value *time.Time) *SkuCreate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilDeletedAt(value *time.Time) *SkuUpdate {
	if value != nil {
		return s.SetDeletedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilDeletedAt(value *time.Time) *SkuUpdateOne {
	if value != nil {
		return s.SetDeletedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilDeletedAt(value *time.Time) *SkuCreate {
	if value != nil {
		return s.SetDeletedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilSpuID(value *uint64) *SkuUpdate {
	if value != nil {
		return s.SetSpuID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilSpuID(value *uint64) *SkuUpdateOne {
	if value != nil {
		return s.SetSpuID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilSpuID(value *uint64) *SkuCreate {
	if value != nil {
		return s.SetSpuID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilProperties(value *[]entType.SkuProperty) *SkuUpdate {
	if value != nil {
		return s.SetProperties(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilProperties(value *[]entType.SkuProperty) *SkuUpdateOne {
	if value != nil {
		return s.SetProperties(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilProperties(value *[]entType.SkuProperty) *SkuCreate {
	if value != nil {
		return s.SetProperties(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilPrice(value *int32) *SkuUpdate {
	if value != nil {
		return s.SetPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilPrice(value *int32) *SkuUpdateOne {
	if value != nil {
		return s.SetPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilPrice(value *int32) *SkuCreate {
	if value != nil {
		return s.SetPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilMarketPrice(value *int32) *SkuUpdate {
	if value != nil {
		return s.SetMarketPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilMarketPrice(value *int32) *SkuUpdateOne {
	if value != nil {
		return s.SetMarketPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilMarketPrice(value *int32) *SkuCreate {
	if value != nil {
		return s.SetMarketPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilCostPrice(value *int32) *SkuUpdate {
	if value != nil {
		return s.SetCostPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilCostPrice(value *int32) *SkuUpdateOne {
	if value != nil {
		return s.SetCostPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilCostPrice(value *int32) *SkuCreate {
	if value != nil {
		return s.SetCostPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilBarCode(value *string) *SkuUpdate {
	if value != nil {
		return s.SetBarCode(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilBarCode(value *string) *SkuUpdateOne {
	if value != nil {
		return s.SetBarCode(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilBarCode(value *string) *SkuCreate {
	if value != nil {
		return s.SetBarCode(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilPicURL(value *string) *SkuUpdate {
	if value != nil {
		return s.SetPicURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilPicURL(value *string) *SkuUpdateOne {
	if value != nil {
		return s.SetPicURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilPicURL(value *string) *SkuCreate {
	if value != nil {
		return s.SetPicURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilStock(value *int32) *SkuUpdate {
	if value != nil {
		return s.SetStock(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilStock(value *int32) *SkuUpdateOne {
	if value != nil {
		return s.SetStock(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilStock(value *int32) *SkuCreate {
	if value != nil {
		return s.SetStock(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilWeight(value *float64) *SkuUpdate {
	if value != nil {
		return s.SetWeight(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilWeight(value *float64) *SkuUpdateOne {
	if value != nil {
		return s.SetWeight(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilWeight(value *float64) *SkuCreate {
	if value != nil {
		return s.SetWeight(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilVolume(value *float64) *SkuUpdate {
	if value != nil {
		return s.SetVolume(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilVolume(value *float64) *SkuUpdateOne {
	if value != nil {
		return s.SetVolume(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilVolume(value *float64) *SkuCreate {
	if value != nil {
		return s.SetVolume(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilFirstBrokeragePrice(value *int32) *SkuUpdate {
	if value != nil {
		return s.SetFirstBrokeragePrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilFirstBrokeragePrice(value *int32) *SkuUpdateOne {
	if value != nil {
		return s.SetFirstBrokeragePrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilFirstBrokeragePrice(value *int32) *SkuCreate {
	if value != nil {
		return s.SetFirstBrokeragePrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilSecondBrokeragePrice(value *float64) *SkuUpdate {
	if value != nil {
		return s.SetSecondBrokeragePrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilSecondBrokeragePrice(value *float64) *SkuUpdateOne {
	if value != nil {
		return s.SetSecondBrokeragePrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilSecondBrokeragePrice(value *float64) *SkuCreate {
	if value != nil {
		return s.SetSecondBrokeragePrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdate) SetNotNilSalesCount(value *int32) *SkuUpdate {
	if value != nil {
		return s.SetSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuUpdateOne) SetNotNilSalesCount(value *int32) *SkuUpdateOne {
	if value != nil {
		return s.SetSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SkuCreate) SetNotNilSalesCount(value *int32) *SkuCreate {
	if value != nil {
		return s.SetSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilUpdatedAt(value *time.Time) *SpuUpdate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilUpdatedAt(value *time.Time) *SpuUpdateOne {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilUpdatedAt(value *time.Time) *SpuCreate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilStatus(value *uint8) *SpuUpdate {
	if value != nil {
		return s.SetStatus(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilStatus(value *uint8) *SpuUpdateOne {
	if value != nil {
		return s.SetStatus(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilStatus(value *uint8) *SpuCreate {
	if value != nil {
		return s.SetStatus(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilSort(value *uint32) *SpuUpdate {
	if value != nil {
		return s.SetSort(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilSort(value *uint32) *SpuUpdateOne {
	if value != nil {
		return s.SetSort(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilSort(value *uint32) *SpuCreate {
	if value != nil {
		return s.SetSort(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilDeletedAt(value *time.Time) *SpuUpdate {
	if value != nil {
		return s.SetDeletedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilDeletedAt(value *time.Time) *SpuUpdateOne {
	if value != nil {
		return s.SetDeletedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilDeletedAt(value *time.Time) *SpuCreate {
	if value != nil {
		return s.SetDeletedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilName(value *string) *SpuUpdate {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilName(value *string) *SpuUpdateOne {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilName(value *string) *SpuCreate {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilKeyword(value *string) *SpuUpdate {
	if value != nil {
		return s.SetKeyword(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilKeyword(value *string) *SpuUpdateOne {
	if value != nil {
		return s.SetKeyword(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilKeyword(value *string) *SpuCreate {
	if value != nil {
		return s.SetKeyword(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilIntroduction(value *string) *SpuUpdate {
	if value != nil {
		return s.SetIntroduction(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilIntroduction(value *string) *SpuUpdateOne {
	if value != nil {
		return s.SetIntroduction(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilIntroduction(value *string) *SpuCreate {
	if value != nil {
		return s.SetIntroduction(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilDescription(value *string) *SpuUpdate {
	if value != nil {
		return s.SetDescription(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilDescription(value *string) *SpuUpdateOne {
	if value != nil {
		return s.SetDescription(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilDescription(value *string) *SpuCreate {
	if value != nil {
		return s.SetDescription(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilBarCode(value *string) *SpuUpdate {
	if value != nil {
		return s.SetBarCode(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilBarCode(value *string) *SpuUpdateOne {
	if value != nil {
		return s.SetBarCode(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilBarCode(value *string) *SpuCreate {
	if value != nil {
		return s.SetBarCode(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilCategoryID(value *uint64) *SpuUpdate {
	if value != nil {
		return s.SetCategoryID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilCategoryID(value *uint64) *SpuUpdateOne {
	if value != nil {
		return s.SetCategoryID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilCategoryID(value *uint64) *SpuCreate {
	if value != nil {
		return s.SetCategoryID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilBrandID(value *uint64) *SpuUpdate {
	if value != nil {
		return s.SetBrandID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilBrandID(value *uint64) *SpuUpdateOne {
	if value != nil {
		return s.SetBrandID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilBrandID(value *uint64) *SpuCreate {
	if value != nil {
		return s.SetBrandID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilPicURL(value *string) *SpuUpdate {
	if value != nil {
		return s.SetPicURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilPicURL(value *string) *SpuUpdateOne {
	if value != nil {
		return s.SetPicURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilPicURL(value *string) *SpuCreate {
	if value != nil {
		return s.SetPicURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilSliderPicUrls(value *[]string) *SpuUpdate {
	if value != nil {
		return s.SetSliderPicUrls(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilSliderPicUrls(value *[]string) *SpuUpdateOne {
	if value != nil {
		return s.SetSliderPicUrls(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilSliderPicUrls(value *[]string) *SpuCreate {
	if value != nil {
		return s.SetSliderPicUrls(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilVideoURL(value *string) *SpuUpdate {
	if value != nil {
		return s.SetVideoURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilVideoURL(value *string) *SpuUpdateOne {
	if value != nil {
		return s.SetVideoURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilVideoURL(value *string) *SpuCreate {
	if value != nil {
		return s.SetVideoURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilUnit(value *uint8) *SpuUpdate {
	if value != nil {
		return s.SetUnit(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilUnit(value *uint8) *SpuUpdateOne {
	if value != nil {
		return s.SetUnit(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilUnit(value *uint8) *SpuCreate {
	if value != nil {
		return s.SetUnit(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilSpecType(value *bool) *SpuUpdate {
	if value != nil {
		return s.SetSpecType(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilSpecType(value *bool) *SpuUpdateOne {
	if value != nil {
		return s.SetSpecType(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilSpecType(value *bool) *SpuCreate {
	if value != nil {
		return s.SetSpecType(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilPrice(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilPrice(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilPrice(value *int32) *SpuCreate {
	if value != nil {
		return s.SetPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilMarketPrice(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetMarketPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilMarketPrice(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetMarketPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilMarketPrice(value *int32) *SpuCreate {
	if value != nil {
		return s.SetMarketPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilCostPrice(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetCostPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilCostPrice(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetCostPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilCostPrice(value *int32) *SpuCreate {
	if value != nil {
		return s.SetCostPrice(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilStock(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetStock(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilStock(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetStock(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilStock(value *int32) *SpuCreate {
	if value != nil {
		return s.SetStock(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilDeliveryTemplateID(value *uint64) *SpuUpdate {
	if value != nil {
		return s.SetDeliveryTemplateID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilDeliveryTemplateID(value *uint64) *SpuUpdateOne {
	if value != nil {
		return s.SetDeliveryTemplateID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilDeliveryTemplateID(value *uint64) *SpuCreate {
	if value != nil {
		return s.SetDeliveryTemplateID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilRecommendHot(value *bool) *SpuUpdate {
	if value != nil {
		return s.SetRecommendHot(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilRecommendHot(value *bool) *SpuUpdateOne {
	if value != nil {
		return s.SetRecommendHot(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilRecommendHot(value *bool) *SpuCreate {
	if value != nil {
		return s.SetRecommendHot(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilRecommendBenefit(value *bool) *SpuUpdate {
	if value != nil {
		return s.SetRecommendBenefit(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilRecommendBenefit(value *bool) *SpuUpdateOne {
	if value != nil {
		return s.SetRecommendBenefit(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilRecommendBenefit(value *bool) *SpuCreate {
	if value != nil {
		return s.SetRecommendBenefit(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilRecommendBest(value *bool) *SpuUpdate {
	if value != nil {
		return s.SetRecommendBest(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilRecommendBest(value *bool) *SpuUpdateOne {
	if value != nil {
		return s.SetRecommendBest(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilRecommendBest(value *bool) *SpuCreate {
	if value != nil {
		return s.SetRecommendBest(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilRecommendNew(value *bool) *SpuUpdate {
	if value != nil {
		return s.SetRecommendNew(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilRecommendNew(value *bool) *SpuUpdateOne {
	if value != nil {
		return s.SetRecommendNew(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilRecommendNew(value *bool) *SpuCreate {
	if value != nil {
		return s.SetRecommendNew(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilRecommendGood(value *bool) *SpuUpdate {
	if value != nil {
		return s.SetRecommendGood(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilRecommendGood(value *bool) *SpuUpdateOne {
	if value != nil {
		return s.SetRecommendGood(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilRecommendGood(value *bool) *SpuCreate {
	if value != nil {
		return s.SetRecommendGood(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilGiveIntegral(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetGiveIntegral(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilGiveIntegral(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetGiveIntegral(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilGiveIntegral(value *int32) *SpuCreate {
	if value != nil {
		return s.SetGiveIntegral(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilGiveCouponTemplateIds(value *[]uint64) *SpuUpdate {
	if value != nil {
		return s.SetGiveCouponTemplateIds(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilGiveCouponTemplateIds(value *[]uint64) *SpuUpdateOne {
	if value != nil {
		return s.SetGiveCouponTemplateIds(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilGiveCouponTemplateIds(value *[]uint64) *SpuCreate {
	if value != nil {
		return s.SetGiveCouponTemplateIds(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilSubCommissionType(value *bool) *SpuUpdate {
	if value != nil {
		return s.SetSubCommissionType(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilSubCommissionType(value *bool) *SpuUpdateOne {
	if value != nil {
		return s.SetSubCommissionType(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilSubCommissionType(value *bool) *SpuCreate {
	if value != nil {
		return s.SetSubCommissionType(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilActivityOrders(value *[]int32) *SpuUpdate {
	if value != nil {
		return s.SetActivityOrders(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilActivityOrders(value *[]int32) *SpuUpdateOne {
	if value != nil {
		return s.SetActivityOrders(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilActivityOrders(value *[]int32) *SpuCreate {
	if value != nil {
		return s.SetActivityOrders(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilSalesCount(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilSalesCount(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilSalesCount(value *int32) *SpuCreate {
	if value != nil {
		return s.SetSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilVirtualSalesCount(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetVirtualSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilVirtualSalesCount(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetVirtualSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilVirtualSalesCount(value *int32) *SpuCreate {
	if value != nil {
		return s.SetVirtualSalesCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdate) SetNotNilBrowseCount(value *int32) *SpuUpdate {
	if value != nil {
		return s.SetBrowseCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuUpdateOne) SetNotNilBrowseCount(value *int32) *SpuUpdateOne {
	if value != nil {
		return s.SetBrowseCount(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SpuCreate) SetNotNilBrowseCount(value *int32) *SpuCreate {
	if value != nil {
		return s.SetBrowseCount(*value)
	}
	return s
}
